spring:
  application:
    name: order-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_dining?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

